# Generated by Django 6.1.1 on 2026-10-06 10:02

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Besok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enhet', models.CharField(max_length=64, unique=True)),
                ('sist_sett', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Handleliste',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('items', models.JSONField(blank=True, default=list)),
                ('history', models.JSONField(blank=True, default=list)),
                ('opprettet', models.DateTimeField(default=django.utils.timezone.now)),
                ('oppdatert', models.DateTimeField(default=django.utils.timezone.now)),
                ('sist_sett', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('navn', models.CharField(blank=True, max_length=200)),
                ('merke', models.CharField(blank=True, max_length=200)),
                ('funnet', models.BooleanField(default=False)),
                ('oppslag_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
